name: pmd 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  pmd-analyse:
    permissions:
      contents: read  # for pmd/pmd-github-action to determine modified files
      pull-requests: read  # for pmd/pmd-github-action to query PRs
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        
    - name: Run PMD Static Code Analysis 
      uses: pmd/pmd-github-action@d57c0463ebba262a33d1983a5c6ac6031bfde43b # v1.4.1
      with:
        rulesets: 'java-basic'
    - name: Extract PMD violations count
      id: extract
      run: |
        echo "::set-output name=violations::$(echo '${{ steps.pmd.outputs.report }}' | grep -o 'Problem: ' | wc -l)"

    - name: Check violations threshold
      run: |
          THRESHOLD=10 # Set your threshold here
          if [ "${{ steps.extract.outputs.violations }}" -gt $THRESHOLD ]; then
            echo "Number of violations exceeds threshold. Failing workflow."
            exit 1
          fi
    
